name: CI/CD Pipeline 

on:
  push:
    branches:
      - feature/copilot-cicd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

# Create a step to upload an artifact named python-app using the current directory (.) as the path.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

          deploy:
            needs: build
            runs-on: ubuntu-latest

            steps:
              - name: Download artifact
                uses: actions/download-artifact@v3
                with:
                  name: python-app

              - name: Deploy to Azure Web App
                uses: azure/webapps-deploy@v2
                with:
                  app-name: <YOUR_APP_NAME>
                  slot-name: production
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: .
