name: Build and Deploy to Azure Web App 

on:
  push:
    branches:
      - feature/workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Set up virtual environment
      run: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "The uvicorn version installed is:"
        uvicorn --version

# Crea un step para subir un artifact con nombre python-app # Con (ctrl + i) + /edit lo toma mejor
    - name: Upload artifact 
      uses: actions/upload-artifact@v4      
      with:
        name: python-app
        path: |
          .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'copilot-demo-2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
     #     startup-command: 'gunicorn -w 2 -k uvicorn.workers.UvicornWorker --b 0.0.0.0:8000 src.app:app'          